################################################################################
# training parameters
################################################################################
train:
  log_dir: 'test'
  model: deeplabv3plus
  weight: imagenet 
  exp_name: test
  lr: 0.01
  lr_policy: poly
  total_itrs: 50000
  step_size: 10000
  batch_size: 16
  val_interval: 3000
  print_interval: 10
  weight_decay: 0.0001
  loss_type: cross_entropy
  output_stride: 16

################################################################################
# dataset parameters
################################################################################
dataset:
  data_root: '/rhome/jhou/data/dataset/scannet/rgbd/'
  classes: 20

################################################################################
# slurm parameters
################################################################################
defaults:
  - hydra/launcher: submitit_slurm
  - hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ${train.log_dir}
  sweep:
    dir: ${train.log_dir}
  launcher:
    partition: debug
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    name: ${hydra.job.name}
    timeout_min: 4320
    cpus_per_task: 8
    gpus_per_node: 1
    exclude: moria
    tasks_per_node: 1
    mem_gb: 32
    nodes: 1
    comment: CriticalExp
    max_num_timeout: 3
